.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. utabit_qt test_utabit_qt
clean: FORCE
	$(MAKE) -C .. utabit_qt_clean test_utabit_qt_clean
check: FORCE
	$(MAKE) -C .. test_utabit_qt_check
utabit-qt utabit-qt.exe: FORCE
	 $(MAKE) -C .. utabit_qt
